### ISSUE TITLE
Broken link in output

### ISSUE THREAD

**Issue by stuft2** [byu-oit/github-action-codedeploy#73]
The link in the output from the action does not work because the account id is redacted.
<img width="1109" alt="Screenshot 2024-10-01 at 12 38 12 PM" src="https://github.com/user-attachments/assets/555f2add-b28f-4b10-885c-d0a60a2e802d">

**Comment by GaryGSC** [comment]
Update your [aws-actions/configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) step. AWS account IDs aren't considered secret, but they were incorrectly marked as secrets in older versions of AWS's action. This has been [fixed since `@v3`](https://github.com/aws-actions/configure-aws-credentials/issues/459), but you might as well go to the current verson, `@v4`.

Refs: [Discussion #195](https://github.com/orgs/byu-oit/discussions/195#discussioncomment-9596474)
